let txt = `•🔞 \`NSFW-18\`
╭───╯
☯️]▸${usedPrefix}hentai
☯️]▸${usedPrefix}genshin
☯️]▸${usedPrefix}rule34
☯️]▸${usedPrefix}swimsuit
☯️]▸${usedPrefix}schoolswimsuit
☯️]▸${usedPrefix}barefoot
☯️]▸${usedPrefix}touhou
☯️]▸${usedPrefix}gamecg
☯️]▸${usedPrefix}hololive
☯️]▸${usedPrefix}uncensored
☯️]▸${usedPrefix}sunglasses
☯️]▸${usedPrefix}glasses
☯️]▸${usedPrefix}weapon
☯️]▸${usedPrefix}shirtlift
☯️]▸${usedPrefix}chain
☯️]▸${usedPrefix}fingering
☯️]▸${usedPrefix}flatchest
☯️]▸${usedPrefix}torncloth
☯️]▸${usedPrefix}bondage
☯️]▸${usedPrefix}demon
☯️]▸${usedPrefix}wet
☯️]▸${usedPrefix}pantypull
☯️]▸${usedPrefix}headdress
☯️]▸${usedPrefix}headphone
☯️]▸${usedPrefix}tie
☯️]▸${usedPrefix}anusview
☯️]▸${usedPrefix}shorts
☯️]▸${usedPrefix}stokings
☯️]▸${usedPrefix}topless
☯️]▸${usedPrefix}beach
☯️]▸${usedPrefix}bunnygirl
☯️]▸${usedPrefix}bunnyear
☯️]▸${usedPrefix}gun
☯️]▸${usedPrefix}maid
☯️]▸${usedPrefix}nobra
☯️]▸${usedPrefix}bikini
☯️]▸${usedPrefix}whitehair
☯️]▸${usedPrefix}blonde
☯️]▸${usedPrefix}pinkhair
☯️]▸${usedPrefix}bed
☯️]▸${usedPrefix}ponytail
☯️]▸${usedPrefix}nude
☯️]▸${usedPrefix}dress
☯️]▸${usedPrefix}underwear
☯️]▸${usedPrefix}foxgirl
☯️]▸${usedPrefix}uniform
☯️]▸${usedPrefix}skirt
☯️]▸${usedPrefix}sex
☯️]▸${usedPrefix}sex2
☯️]▸${usedPrefix}sex3
☯️]▸${usedPrefix}breast
☯️]▸${usedPrefix}twintail
☯️]▸${usedPrefix}spreadpussy
☯️]▸${usedPrefix}tears
☯️]▸${usedPrefix}seethrough
☯️]▸${usedPrefix}breasthold
☯️]▸${usedPrefix}drunk
☯️]▸${usedPrefix}fateseries
☯️]▸${usedPrefix}spreadlegs
☯️]▸${usedPrefix}openshirt
☯️]▸${usedPrefix}headband
☯️]▸${usedPrefix}food
☯️]▸${usedPrefix}tree
☯️]▸${usedPrefix}nipples
☯️]▸${usedPrefix}erectnipples
☯️]▸${usedPrefix}horns
☯️]▸${usedPrefix}greenhair
☯️]▸${usedPrefix}wolfgirl
☯️]▸${usedPrefix}catgirl
☯️]▸${usedPrefix}genshin
☯️]▸${usedPrefix}swimsuit
☯️]▸${usedPrefix}schoolswimsuit
☯️]▸${usedPrefix}white
☯️]▸${usedPrefix}barefoot
☯️]▸${usedPrefix}touhou
☯️]▸${usedPrefix}gamecg
☯️]▸${usedPrefix}hololive
☯️]▸${usedPrefix}uncensored
☯️]▸${usedPrefix}sunglasses
☯️]▸${usedPrefix}glasses
☯️]▸${usedPrefix}weapon
☯️]▸${usedPrefix}shirtlift
☯️]▸${usedPrefix}chain
☯️]▸${usedPrefix}fingering
☯️]▸${usedPrefix}flatchest
☯️]▸${usedPrefix}torncloth
☯️]▸${usedPrefix}bondage
☯️]▸${usedPrefix}demon
☯️]▸${usedPrefix}pantypull
☯️]▸${usedPrefix}headdress
☯️]▸${usedPrefix}headphone
☯️]▸${usedPrefix}anusview
☯️]▸${usedPrefix}shorts
☯️]▸${usedPrefix}stokings
☯️]▸${usedPrefix}topless
☯️]▸${usedPrefix}beach
☯️]▸${usedPrefix}bunnygirl
☯️]▸${usedPrefix}bunnyear
☯️]▸${usedPrefix}idol
☯️]▸${usedPrefix}vampire
☯️]▸${usedPrefix}gun
☯️]▸${usedPrefix}maid
☯️]▸${usedPrefix}bra
☯️]▸${usedPrefix}nobra
☯️]▸${usedPrefix}bikini
☯️]▸${usedPrefix}whitehair
☯️]▸${usedPrefix}blonde
☯️]▸${usedPrefix}pinkhair
☯️]▸${usedPrefix}bed
☯️]▸${usedPrefix}ponytail
☯️]▸${usedPrefix}dude
☯️]▸${usedPrefix}dress
☯️]▸${usedPrefix}underwear
☯️]▸${usedPrefix}foxgirl
☯️]▸${usedPrefix}uniform
☯️]▸${usedPrefix}skirt
☯️]▸${usedPrefix}breast
☯️]▸${usedPrefix}twintail
☯️]▸${usedPrefix}spreadpussy
☯️]▸${usedPrefix}tears
☯️]▸${usedPrefix}seethrough
☯️]▸${usedPrefix}breasthold
☯️]▸${usedPrefix}drunk
☯️]▸${usedPrefix}fateseries
☯️]▸${usedPrefix}spreadlegs
☯️]▸${usedPrefix}openshirt
☯️]▸${usedPrefix}headband
☯️]▸${usedPrefix}food
☯️]▸${usedPrefix}close
☯️]▸${usedPrefix}tree
☯️]▸${usedPrefix}nipples
☯️]▸${usedPrefix}erectnipples
☯️]▸${usedPrefix}horns
☯️]▸${usedPrefix}greenhair
☯️]▸${usedPrefix}wolfgirl
☯️]▸${usedPrefix}catgirl
╰───╮╭───╯

𝗉𝗈𝗐𝖾𝗋𝖾𝖽 ⓒ 𝖨𝗓𝗎𝗆𝗂-𝖻𝗈𝗍 𝟤𝟢𝟤𝟢-𝟤𝟢𝟤𝟦.`
m.react('🛐')
conn.sendMessage(m.chat, { text: txt, contextInfo: { externalAdReply: {title: `${await conn.getName(m.chat)}`, body: wm, thumbnailUrl: imagen4, thumbnail: imagen4, showAdAttribution: true, sourceUrl: canal}}} , { quoted: m})
}
handler.command = ['menunsfw', 'menu2']
handler.group = true
export default handler
